import { escapeHTML as h, safeURL, safeImageURL, eventRoute, eventLabel, eventUnderstanding, eventMatchesId, excerpt, formatDate, coverageText, latestPublications, sourceLabel, publicationLanguage, modesForPreferences, MODES, DEFAULT_PREFS } from './model.mjs?v=20261007-steam1';

const paths = {
  home: '<path d="m3 11 9-8 9 8M5 10v11h5v-7h4v7h5V10"/>',
  search: '<circle cx="10.5" cy="10.5" r="7"/><path d="m16 16 5 5"/>',
  library: '<path d="M4 4h4v17H4zM11 4h4v17h-4zM18 4l4 16-4 1-4-16z"/>',
  inbox: '<path d="M5 17h14l-2-4V9a5 5 0 0 0-10 0v4zM10 21h4"/>',
  settings: '<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',
  check: '<path d="m5 12 4 4L19 6"/>',
  arrow: '<path d="m14 5-7 7 7 7"/>',
  plus: '<path d="M12 4v16M4 12h16"/>',
  refresh: '<path d="M20 7v5h-5M4 17v-5h5M5 8a8 8 0 0 1 13-3l2 2M4 17l2 2a8 8 0 0 0 13-3"/>',
  external: '<path d="M14 3h7v7M21 3 10 14M10 5H4v16h16v-6"/>',
};
export function icon(name, extra = '') { return `<svg class="icon ${extra}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.home}</svg>`; }

export function art(game, className = '', lazy = true) {
  const url = safeImageURL(game.image_url);
  return url ? `<img class="game-art ${className}" src="${h(url)}" alt="" ${lazy ? 'loading="lazy"' : ''} decoding="async" referrerpolicy="no-referrer">` : `<div class="game-art art-fallback ${className}" aria-hidden="true">${h(game.name?.slice(0, 2) || 'Игра')}</div>`;
}

export function externalLink(url, label, className = '') {
  const valid = safeURL(url);
  return valid ? `<a class="${className}" href="${h(valid)}" target="_blank" rel="noopener noreferrer">${h(label)} ${icon('external')}</a>` : '';
}

function applicationLabel(game, detail = false) {
  return game.type === 'dlc' ? (detail ? 'Дополнение DLC' : 'DLC') : game.type === 'steam_app' ? 'Приложение из Steam' : (detail ? 'Игра Steam' : 'Игра');
}

export function shell(route, bootstrap) {
  const active = ['game', 'settings', 'feed'].includes(route.page) ? 'library' : route.page;
  const nav = [['home', 'Главная'], ['search', 'Поиск'], ['library', 'Библиотека'], ['inbox', 'Уведомления']].map(([key, label]) => `<a class="nav-item ${active === key ? 'active' : ''}" href="#${key}" ${active === key ? 'aria-current="page"' : ''}>${icon(key)}<span>${label}</span>${key === 'inbox' ? '<span class="unread-count" data-unread' + (!bootstrap?.unread_count ? ' hidden' : '') + '>' + h(bootstrap?.unread_count || '') + '</span>' : ''}</a>`).join('');
  const running = bootstrap?.health?.worker_running;
  return `<div class="app-layout">
    <aside class="sidebar"><a class="brand" href="#home"><svg class="brand-mark" viewBox="0 0 42 42" aria-hidden="true"><circle cx="21" cy="21" r="16"/><circle cx="21" cy="21" r="8"/><path d="M21 5v16l12-8"/><circle class="radar-dot" cx="21" cy="21" r="2.7"/></svg><span>Игровой<br>радар</span></a>
    <nav class="desktop-nav" aria-label="Основная навигация">${nav}</nav>
    <div class="sidebar-bottom"><span class="connection-status"><i class="status-dot ${running ? 'is-running' : ''}"></i>${running ? 'Проверка игр работает' : 'Проверка игр приостановлена'}</span><p>Черновая версия<br>Развиваем постепенно</p></div></aside>
    <div class="workspace"><header class="topbar"><a class="mobile-brand" href="#home">Игровой радар</a><div class="topbar-context">Всё об обновлениях ваших игр</div><a class="profile-pill" href="#profile" aria-label="Открыть мой профиль"><span class="avatar" aria-hidden="true">${h((bootstrap?.profile?.name || 'М').slice(0, 1))}</span><span>${h(bootstrap?.profile?.name || 'Мой профиль')}<small>${bootstrap?.profile?.local_only === false ? 'Профиль Telegram' : 'В этом браузере'}</small></span></a></header>
      <main id="main-content" tabindex="-1"></main>
    </div><nav class="mobile-nav" aria-label="Навигация на телефоне">${nav}</nav>
  </div>`;
}

export function pageHeader(title, text, actions = '') {
  return `<div class="page-heading"><div><h1>${h(title)}</h1>${text ? `<p>${h(text)}</p>` : ''}</div>${actions ? `<div class="heading-actions">${actions}</div>` : ''}</div>`;
}

export function emptyState(title, text, action = '') {
  return `<div class="empty-state"><div class="empty-symbol">${icon('library')}</div><h2>${h(title)}</h2><p>${h(text)}</p>${action}</div>`;
}

export function errorState(message, retry = 'retry') {
  return `<div class="error-state" role="alert"><h2>Не получилось загрузить</h2><p>${h(message)}</p><button class="button secondary" type="button" data-action="${retry}">Попробовать снова</button></div>`;
}

export function loadingState(text = 'Загружаем данные…') {
  return `<div class="loading-state" role="status"><span class="loading-orbit" aria-hidden="true"></span>${h(text)}</div>`;
}

export function connectionScreen(error, config = {}) {
  const isLogin = error.code === 'telegram_required';
  const expired = ['auth_expired', 'invalid_auth'].includes(error.code);
  const title = isLogin ? 'Откройте радар в Telegram' : expired ? 'Откройте приложение снова' : error.code === 'not_configured' ? 'Готовим подключение' : error.code === 'telegram_unavailable' ? 'Не удалось подключить Telegram' : ['offline', 'timeout', 'invalid_response'].includes(error.code) ? 'Домашний сервер недоступен' : 'Не удалось открыть приложение';
  return `<main id="main-content" tabindex="-1" class="connection-screen"><div class="connection-card"><a class="connection-brand" href="#home">Игровой радар</a><div class="empty-symbol">${icon(isLogin || expired ? 'inbox' : 'refresh')}</div><h1>${h(title)}</h1><p>${h(error.message || 'Не удалось подключиться к серверу.')}</p>${!isLogin && !expired ? '<p class="connection-explanation">Приложение получает данные с домашнего компьютера. Он должен быть включён, а сервер приложения — запущен. Открытая страница сама не запускает отслеживание.</p>' : '<p class="connection-explanation">Вход подтверждается Telegram. Библиотека и настройки будут доступны после открытия кнопкой в боте.</p>'}<div class="connection-actions">${externalLink(config.botURL, 'Открыть бота', 'button primary')}<button class="button secondary" type="button" data-action="retry">Попробовать снова</button></div></div></main>`;
}

export function deliveryControls(profile, config = {}, status = {}) {
  if (profile?.local_only !== false) return '';
  const enabled = profile.telegram_delivery_enabled;
  const canMessage = profile.telegram_can_message;
  const configured = status.configured !== false;
  const blocked = status.state === 'blocked';
  const warning = !configured ? 'Доставка на сервере пока не настроена.' : blocked ? 'Бот не может отправить сообщение. Откройте его, разблокируйте и нажмите «Начать».' : status.sender_available === false ? 'Отправщик сейчас недоступен. События сохраняются в истории; доставка требует восстановления сервера.' : Number(status.failed_count) > 0 ? 'Есть сообщения, которые пока не удалось доставить. Попробуйте проверку доставки.' : '';
  const testStatus = status.last_test_at ? `<p class="delivery-status">Проверка доставки ${h(formatDate(status.last_test_at, true))}: ${status.last_test_ok === true ? 'тест отправлен' : status.last_test_ok === false ? 'отправка не удалась' : 'результат пока неизвестен'}.</p>` : '';
  return `<section class="telegram-delivery ${enabled ? 'delivery-enabled' : 'delivery-disabled'}" aria-label="Доставка в Telegram"><div class="delivery-copy"><h3>Сообщения от бота <span class="delivery-badge">${enabled ? 'Включены' : 'Выключены'}</span></h3><p>${enabled ? 'Новые события придут в чат с ботом по настройкам ваших игр.' : 'Режим игры выбирает события. Чтобы они приходили в чат с ботом, отдельно включите доставку в Telegram.'} Старые публикации не рассылаются.</p>${warning ? `<p class="delivery-warning" role="status">${h(warning)}</p>` : !canMessage ? '<p class="delivery-warning">Откройте бота и нажмите «Начать», чтобы он мог присылать сообщения.</p>' : ''}${status.last_sent_at ? `<p class="delivery-status">Последнее уведомление о событии отправлено: ${h(formatDate(status.last_sent_at, true))}</p>` : '<p class="delivery-status">Уведомлений о новых событиях этому профилю ещё не отправляли.</p>'}${testStatus}${Number(status.pending_count) > 0 ? `<p class="delivery-status">Ожидают отправки: ${h(status.pending_count)}</p>` : ''}${status.next_delivery_at ? `<p class="delivery-status">Запланированная отправка: ${h(scheduledDate(status.next_delivery_at, status.schedule?.utc_offset_minutes ?? 180))} в выбранном часовом поясе.</p>` : ''}</div><div class="delivery-actions">${configured && canMessage && !blocked ? `<button class="button ${enabled ? 'secondary' : 'primary'}" type="button" data-action="delivery" data-enabled="${enabled ? 'false' : 'true'}">${enabled ? 'Отключить сообщения' : 'Включить сообщения'}</button><button class="button secondary" type="button" data-action="delivery-test">Проверить доставку</button><small>Проверка отправит одно тестовое сообщение только вам.</small>` : `${externalLink(config.botURL, 'Открыть бота', 'button primary')}${configured ? '<button class="button secondary" type="button" data-action="write-access">Разрешить уведомления</button>' : ''}${enabled ? '<button class="button secondary" type="button" data-action="delivery" data-enabled="false">Отключить сообщения</button>' : ''}`}</div>${deliveryScheduleForm(status.schedule)}</section>`;
}

function scheduledDate(value, offset = 180) {
  const epoch = Date.parse(value);
  if (!Number.isFinite(epoch)) return '';
  return new Intl.DateTimeFormat('ru-RU', { day:'numeric', month:'long', hour:'2-digit', minute:'2-digit', timeZone:'UTC' }).format(new Date(epoch + offset * 60000));
}

export function deliveryScheduleForm(value = {}) {
  const schedule = { mode: 'instant', daily_time: '20:00', utc_offset_minutes: 180, quiet_enabled: false, quiet_start: '23:00', quiet_end: '08:00', ...value };
  const offsets = [...new Set([...Array.from({ length: 27 }, (_, i) => (i - 12) * 60), 330, 345, 570, 765, Number(schedule.utc_offset_minutes)])].sort((a, b) => a - b);
  const offsetLabel = offset => `UTC${offset < 0 ? '−' : '+'}${String(Math.floor(Math.abs(offset) / 60)).padStart(2, '0')}:${String(Math.abs(offset) % 60).padStart(2, '0')}${offset === 180 ? ' · Москва' : ''}`;
  const caption = schedule.mode === 'digest' ? `Сводка в ${schedule.daily_time}` : 'Сразу после обнаружения';
  return `<details class="delivery-schedule"><summary><span class="schedule-caption">${h(caption)}</span> · изменить расписание</summary><form id="delivery-schedule-form"><div class="schedule-grid"><label class="schedule-field">Как отправлять<select name="mode"><option value="instant" ${schedule.mode === 'instant' ? 'selected' : ''}>Каждое событие сразу</option><option value="digest" ${schedule.mode === 'digest' ? 'selected' : ''}>Одной сводкой за день</option></select></label><label class="schedule-field">Часовой пояс<select name="utc_offset_minutes">${offsets.map(offset => `<option value="${h(offset)}" ${offset === Number(schedule.utc_offset_minutes) ? 'selected' : ''}>${h(offsetLabel(offset))}</option>`).join('')}</select></label><label class="schedule-field schedule-daily" ${schedule.mode !== 'digest' ? 'hidden' : ''}>Время сводки<input type="time" name="daily_time" required ${schedule.mode !== 'digest' ? 'disabled' : ''} value="${h(schedule.daily_time)}"></label></div><p class="schedule-explanation">Сводка содержит события, прошедшие фильтры ваших игр. Если ничего нового нет, сообщение не приходит. При выключенном ПК отправка ждёт запуска сервера.</p><label class="schedule-quiet"><input type="checkbox" name="quiet_enabled" ${schedule.quiet_enabled ? 'checked' : ''}>Тихие часы</label><div class="schedule-grid schedule-quiet-times" ${!schedule.quiet_enabled ? 'hidden' : ''}><label class="schedule-field">Не присылать с<input type="time" name="quiet_start" required ${!schedule.quiet_enabled ? 'disabled' : ''} value="${h(schedule.quiet_start)}"></label><label class="schedule-field">До<input type="time" name="quiet_end" required ${!schedule.quiet_enabled ? 'disabled' : ''} value="${h(schedule.quiet_end)}"></label></div><p class="schedule-explanation">Во время тихих часов события копятся и приходят одной сводкой после их окончания. Время считается в выбранном часовом поясе; переход на летнее время автоматически не учитывается.</p><div class="schedule-save"><button type="submit" class="button secondary">Сохранить расписание</button><span id="schedule-message" role="status"></span></div></form></details>`;
}

export function eventSummary(event, preferred = 'ru', compact = false) {
  const analysis = eventUnderstanding(event, preferred);
  const language = publicationLanguage(event, preferred);
  const title = analysis.category === 'announcement' ? 'О чём публикация' : 'Что изменилось';
  if (analysis.summary_points.length) return `<div class="change-summary ${compact ? 'summary-compact' : ''}"><h4>${title}</h4><ul>${analysis.summary_points.slice(0, compact ? 2 : 4).map(point => `<li>${h(point)}</li>`).join('')}</ul><p class="summary-basis">${analysis.summary_original ? 'Выдержки из оригинала разработчика.' : analysis.summary_translated ? 'Выдержки из автоматического перевода. Оригинал доступен в полной карточке.' : 'Выдержки из текста разработчика.'} ${event.contents_truncated || analysis.summary_points.length > (compact ? 2 : 4) ? 'Полный список изменений смотрите в источнике.' : 'Это краткий фрагмент, а не полный список изменений.'}</p></div>`;
  return `<p class="event-excerpt">${h(excerpt(language.contents, compact ? 180 : 260) || (event.kind === 'public_build_changed' ? 'Изменился номер сборки игры. Что именно изменилось, пока неизвестно.' : 'Описание пока не получено. Доступны заголовок и ссылка на источник.'))}</p>`;
}

export function eventEvidence(event, preferred = 'ru', expanded = false) {
  const analysis = eventUnderstanding(event, preferred);
  if (!event.understanding) return '';
  const changeLabels = { content: 'Новый контент', balance: 'Баланс', fixes: 'Исправления', performance: 'Производительность', technical: 'Технические изменения' };
  const labels = analysis.change_types.filter(type => changeLabels[type]).map(type => changeLabels[type]);
  const update = ['update', 'unknown'].includes(analysis.category);
  const versions = analysis.version_labels.slice(0, 3);
  const reasons = [analysis.category_reason_ru, ...(update ? [analysis.importance_reason_ru, analysis.severity_reason_ru] : [])].filter(Boolean);
  const uniqueReasons = [...new Set(reasons)];
  return `<div class="event-evidence">${update ? `<span class="importance-label ${analysis.importance_level === 'important' ? 'importance-major' : ''}">${h(analysis.importance_label)}</span>` : ''}${labels.map(label => `<span class="change-tag">${h(label)}</span>`).join('')}${versions.map(version => `<span class="change-tag">Версия ${h(version)}</span>`).join('')}</div>${expanded && uniqueReasons.length ? `<details class="classification-explanation"><summary>Почему так определено</summary>${uniqueReasons.map(reason => `<p>${h(reason)}</p>`).join('')}<p>Определяем по словам и явным признакам в исходной публикации. Если данных мало, оставляем оценку неизвестной.</p></details>` : ''}`;
}

function relatedSources(event, expanded = false) {
  const related = Array.isArray(event.related_events) ? event.related_events.filter(item => String(item.id) !== String(event.id)) : [];
  if (!related.length) return '';
  return `<details class="related-sources" ${expanded ? 'open' : ''}><summary>Ещё источники об этом обновлении: ${related.length}</summary><p>${h(event.grouping_reason_ru || 'Источники связаны одной публикацией или явно указанным номером сборки. Совпадение времени или версии само по себе не объединяет события.')}</p><ul>${related.map(item => `<li>${item.kind === 'public_build_changed' ? `<span>Новая сборка игры${item.new_build_id ? ' · номер сборки ' + h(item.new_build_id) : ''}</span>` : externalLink(item.url, item.title || sourceLabel(item.source), 'source-link') || `<span>${h(item.title || sourceLabel(item.source))}</span>`}</li>`).join('')}</ul></details>`;
}

export function addButton(game, library, compact = false) {
  const added = library.some(item => Number(item.app_id) === Number(game.app_id));
  return added ? `<a class="button ${compact ? 'small ' : ''}quiet in-library" href="#game/${game.app_id}" aria-label="Открыть ${h(game.name)} в библиотеке">${icon('check')}В библиотеке</a>` : `<button class="button ${compact ? 'small ' : ''}primary" type="button" data-action="add" data-app-id="${game.app_id}" aria-label="Добавить ${h(game.name)} в библиотеку">${icon('plus')}Добавить</button>`;
}

export function gameRow(game, library, { actions = true, preferences = false } = {}) {
  const mode = MODES.find(item => item.id === game.preferences?.mode)?.name;
  return `<div class="game-row"><a href="#game/${game.app_id}" class="game-row-main">${art(game)}<div class="game-row-copy"><h3>${h(game.name)}</h3><div class="row-meta"><span class="type-label">${applicationLabel(game)}</span>${preferences && mode ? `<span>${game.preferences.enabled ? h(mode) : 'Уведомления выключены'}</span>` : `<span>${h(coverageText(game))}</span>`}</div>${game.latest_event ? `<p>${h(publicationLanguage(game.latest_event).title)}</p>` : ''}</div></a>${actions ? `<div class="row-actions">${preferences ? `<a class="icon-button" href="#settings/${game.app_id}" aria-label="Настройки ${h(game.name)}">${icon('settings')}</a>` : addButton(game, library, true)}</div>` : ''}</div>`;
}

export function homePage(bootstrap, config = {}) {
  const featured = bootstrap.featured || [];
  const library = bootstrap.library || [];
  const publications = latestPublications(featured).slice(0, 3);
  return `${pageHeader('Главная', 'Последние публикации и игры, за которыми стоит следить.', '<a class="button secondary" href="#search">' + icon('search') + 'Найти игру</a>')}
    ${feedEntry(library)}${deliveryControls(bootstrap.profile, config, bootstrap.delivery_status)}<section class="bulletin-section" aria-labelledby="bulletin-title"><div class="section-heading"><h2 id="bulletin-title">Из последних обновлений</h2><span class="subtle">Официальные источники</span></div>
    ${publications.length ? `<div class="bulletin-grid">${publications.map((game, index) => `<article class="bulletin ${index === 0 ? 'bulletin-lead' : ''}">${art(game, '', index !== 0)}<div class="bulletin-body"><a class="bulletin-game" href="#game/${game.app_id}">${h(game.name)}</a><div class="event-meta"><span>${h(eventLabel(game.latest_event))}</span><time>${h(formatDate(game.latest_event.published_at || game.latest_event.sort_at))}</time></div><h3><a href="${eventRoute(game.latest_event)}">${h(publicationLanguage(game.latest_event).title)}</a></h3>${eventEvidence(game.latest_event)}${eventSummary(game.latest_event, 'ru', true)}<a class="bulletin-link" href="${eventRoute(game.latest_event)}">Открыть обновление ${icon('external')}</a></div></article>`).join('')}</div>` : `<div class="inline-empty"><h3>Первые публикации появятся после проверки</h3><p>Можно уже выбрать игры и собрать библиотеку. Если источник недоступен, это будет видно на странице игры.</p></div>`}</section>
    <div class="home-columns"><section class="featured-section" aria-labelledby="featured-title"><div class="section-heading"><h2 id="featured-title">Известные игры</h2><a class="text-link" href="#search">Открыть поиск</a></div><div class="game-list">${featured.map(game => gameRow(game, library)).join('') || '<p class="subtle">Подборка ещё не загружена. Найдите интересующую игру в поиске.</p>'}</div></section>
    <section class="personal-section" aria-labelledby="personal-title"><div class="section-heading"><h2 id="personal-title">Ваша библиотека</h2><a class="text-link" href="#library">Открыть</a></div>${library.length ? `<div class="game-list compact-list">${library.slice(0, 4).map(game => gameRow(game, library, { actions: false, preferences: true })).join('')}</div>` : `<div class="library-invitation"><div class="empty-symbol">${icon('library')}</div><h3>Соберите свой список</h3><p>Добавьте игры, которые вам интересны. Для каждой можно выбрать собственный режим уведомлений.</p><a class="button primary" href="#search">${icon('plus')}Добавить первую игру</a></div>`}<div class="home-note"><span class="note-mark" aria-hidden="true">i</span><p>Сохраняем найденные события в историю. Ваши настройки определяют, о чём появится уведомление.</p></div></section></div>`;
}

export function searchPage(query = '', kind = 'game') {
  return `${pageHeader('Поиск игр', 'Найдите игру в Steam и добавьте её в свою библиотеку.')}
    <form id="search-form" class="search-form" role="search"><div class="search-field">${icon('search')}<label class="sr-only" for="search-input">Название игры или Steam AppID</label><input id="search-input" name="q" type="search" value="${h(query)}" placeholder="Название игры или Steam AppID" autocomplete="off" enterkeyhint="search"><button class="search-submit" type="submit" aria-label="Найти игру">Найти</button></div><fieldset class="type-filters"><legend class="sr-only">Тип приложения Steam</legend>${[['game', 'Игры'], ['dlc', 'DLC'], ['all', 'Всё']].map(([value, label]) => `<label><input type="radio" name="kind" value="${value}" ${value === kind ? 'checked' : ''}><span>${label}</span></label>`).join('')}</fieldset></form>
    <div id="search-results" aria-live="polite">${query ? loadingState('Ищем в каталоге Steam…') : emptyState('Какая игра вас интересует?', 'Начните с названия. DLC можно искать отдельно или вместе с играми.')}</div>`;
}

export function searchResults(result, library) {
  const games = result.games || [];
  return `${result.notice ? `<div class="notice">${h(result.notice)}</div>` : ''}${result.status === 'partial' ? '<p class="source-warning">Каталог доступен частично. Если игры нет, попробуйте точное название или AppID.</p>' : ''}${games.length ? `<div class="section-heading search-results-heading"><h2>Результаты поиска</h2><span class="subtle">${games.length} найдено</span></div><div class="game-list search-list">${games.map(game => gameRow(game, library)).join('')}</div><p class="page-footnote">Игра в каталоге может иметь неполные источники обновлений. После добавления проверим, какие данные доступны.</p>` : emptyState('Ничего не найдено', 'Проверьте название, смените фильтр или укажите Steam AppID.')}`;
}

export function libraryPage(games, profile = {}, config = {}, deliveryStatus = {}) {
  return `${pageHeader('Библиотека', 'Ваши игры и личные правила уведомлений.', '<a class="button primary" href="#search">' + icon('plus') + 'Добавить игру</a>')}${feedEntry(games)}<div class="library-transfer-actions"><button class="button secondary" type="button" data-action="steam-open">Импортировать из Steam</button><button class="button secondary" type="button" data-action="library-transfer-open">Добавить списком</button><button class="button quiet" type="button" data-action="library-export">Сохранить библиотеку</button></div><section id="steam-panel" hidden></section>${libraryTransferPanel()}${deliveryControls(profile, config, deliveryStatus)}${games.length ? `<div class="game-list library-list">${games.map(game => gameRow(game, games, { preferences: true })).join('')}</div><p class="page-footnote">Это ваш список отслеживания. Владеть игрой в Steam, чтобы добавить её сюда, не требуется.</p>` : emptyState('Здесь будут ваши игры', 'Добавьте одну или несколько игр. История общая, а режим уведомлений для каждой игры выбираете вы.', '<a class="button primary" href="#search">Найти первую игру</a>')}`;
}

export function profilePage(profile = {}) {
  return `<a class="back-link" href="#library">${icon('arrow')}Библиотека</a>${pageHeader('Мой профиль', profile.name || 'Ваш профиль в приложении')}<section id="steam-panel"></section>`;
}

export function steamPanel(data = {}, selection = {}, filtered = []) {
  const status = data.status;
  const busy = Boolean(data.busy);
  const account = status?.account;
  const existing = selection.existing || new Set();
  const slots = selection.slots ?? 100;
  const games = selection.games || [];
  const controls = status?.connected ? `<div class="steam-account"><strong>Steam подключён</strong>${externalLink(account?.profile_url, 'Открыть Steam-профиль', 'text-link')}<small>SteamID ${h(account?.steam_id)}</small></div><div class="library-transfer-actions"><button class="button secondary" type="button" data-action="steam-library" ${busy ? 'disabled' : ''}>${data.loaded ? 'Обновить список Steam' : 'Загрузить мои игры'}</button><button class="button quiet" type="button" data-action="steam-unlink" ${busy ? 'disabled' : ''}>Отвязать Steam</button></div><p class="subtle">Отвязка удаляет подключение Steam. Добавленные игры, история и настройки остаются в радаре.</p>` : status ? `<button class="button primary" type="button" data-action="steam-connect" ${busy ? 'disabled' : ''}>${status.pending ? 'Начать вход заново' : 'Подключить Steam'}</button>` : '';
  const pending = status?.pending ? `<p class="notice">Ожидаем подтверждение в Steam. После входа вернитесь сюда. Ссылка действует до ${h(formatDate(status.pending.expires_at, true))}.</p>` : '';
  const unavailable = status?.connected && status.key_configured === false ? '<p class="notice">Импорт пока недоступен: владелец сервиса ещё не настроил загрузку игр из Steam. Ваш API-ключ не нужен. Подключённый профиль сохранён; попробуйте загрузить список позже.</p>' : '';
  const preview = data.loaded ? `<div class="steam-preview"><h3>Выберите игры для отслеживания</h3><p class="subtle">Найдено в Steam: ${games.length}. Уже отслеживаются: ${games.filter(game => existing.has(game.app_id)).length}. Можно добавить ещё: ${slots} из 100.</p><p class="subtle">Список Steam API может отличаться от библиотеки в клиенте Steam. Семейные игры здесь не загружаются; некоторые DLC и отдельные лицензии Steam может не вернуть. Недостающую игру можно добавить через обычный поиск. Подтверждённые программы и другие приложения, кроме игр и DLC, пропускаем при добавлении.</p><label class="transfer-label" for="steam-game-search">Поиск среди моих игр</label><input id="steam-game-search" class="steam-search" type="search" value="${h(selection.query || '')}" placeholder="Название или AppID" ${busy ? 'disabled' : ''}><div id="steam-game-results">${steamSelectionRows(data, selection, filtered)}</div><p class="subtle">Импорт не включает сообщения автоматически. Новые игры получат режим «Все обновления»; настройки уже добавленных игр сохранятся. Большой выбор добавляем частями — подтверждённые игры остаются при ошибке.</p></div>` : '';
  return `<div class="library-transfer steam-import" aria-labelledby="steam-import-title" aria-busy="${busy}"><div class="section-heading"><h2 id="steam-import-title">Библиотека Steam</h2>${data.profile ? '' : `<button class="button small quiet" type="button" data-action="steam-close" ${busy ? 'disabled' : ''}>Свернуть</button>`}</div><p class="subtle">Вход проходит на настоящем сайте Steam. Радар получает номер профиля и доступный список игр. Сохраняем подключение и выбранные игры. Пароль, коды Steam Guard и ваш API-ключ не нужны.</p>${controls}${pending}${unavailable}${data.loginURL ? `<p><button class="button primary" type="button" data-action="steam-continue" ${busy ? 'disabled' : ''}>Продолжить в Steam ${icon('external')}</button></p>` : ''}${data.busy ? loadingState(data.busy) : ''}${data.message ? `<p class="transfer-message" role="status" aria-live="polite">${h(data.message)}</p>` : ''}${data.error ? `<p class="notice" role="alert">${h(data.error)}</p>` : ''}<button class="button small quiet" type="button" data-action="steam-check" ${busy ? 'disabled' : ''}>Проверить подключение</button>${preview}</div>`;
}

export function steamSelectionRows(data = {}, selection = {}, filtered = []) {
  const busy = Boolean(data.busy);
  const selected = selection.selected || new Set();
  const existing = selection.existing || new Set();
  const skipped = selection.skipped || new Map();
  const slots = selection.slots ?? 100;
  const shown = filtered.slice(0, selection.shown || 60);
  return `<div class="steam-selection-actions"><button class="button small quiet" type="button" data-action="steam-select" ${busy || !slots || !filtered.some(game => !existing.has(game.app_id) && !skipped.has(game.app_id)) ? 'disabled' : ''}>Выбрать найденные (до ${slots})</button><button class="button small quiet" type="button" data-action="steam-clear" ${busy || !selected.size ? 'disabled' : ''}>Снять весь выбор</button><span class="subtle" id="steam-selection-count">Выбрано: ${selected.size} / ${slots}</span></div>${shown.length ? `<div class="transfer-game-list steam-game-list">${shown.map(game => { const tracked = existing.has(game.app_id); const checked = selected.has(game.app_id); return `<label class="transfer-game ${tracked ? 'already-tracked' : ''}"><input type="checkbox" data-steam-id="${game.app_id}" ${checked ? 'checked' : ''} ${busy || tracked || skipped.has(game.app_id) || !checked && selected.size >= slots ? 'disabled' : ''}><span><strong>${h(game.name)}</strong><small>AppID ${game.app_id}${tracked ? ' · Уже отслеживается, настройки сохраняются' : skipped.has(game.app_id) ? ` · Пропущено: ${h(skipped.get(game.app_id))}` : ''}</small></span></label>`; }).join('')}</div>` : '<p class="subtle">Подходящих игр в полученном списке нет.</p>'}${filtered.length > shown.length ? `<button class="button small secondary" type="button" data-action="steam-more" ${busy ? 'disabled' : ''}>Показать ещё (${shown.length} из ${filtered.length})</button>` : ''}<div class="steam-import-submit"><button class="button primary" type="button" data-action="steam-import" ${busy || !selected.size ? 'disabled' : ''}>Добавить выбранные (${selected.size})</button></div>${!slots ? '<p class="notice">В радаре уже 100 игр. Чтобы добавить другие, сначала уберите ненужные из отслеживания.</p>' : ''}`;
}

export function steamCallbackScreen(data = {}, config = {}) {
  const done = data.done;
  return `<main id="main-content" tabindex="-1" class="connection-screen"><div class="connection-card"><span class="connection-brand">Игровой радар</span><h1>${done ? 'Steam подключён' : data.error ? 'Подключение Steam не завершено' : 'Проверяем вход в Steam…'}</h1>${done ? '<p>Вернитесь в приложение через бота и выберите игры для отслеживания. Без вашего выбора игры не добавляются.</p>' : data.error ? `<p role="alert">${h(data.error)}</p>` : loadingState('Подтверждаем ответ Steam…')}<div class="connection-actions">${externalLink(config.botURL, 'Вернуться в Telegram', 'button primary')}${data.retry ? '<button class="button secondary" type="button" data-action="steam-callback-retry">Повторить проверку</button>' : ''}</div></div></main>`;
}

function feedEntry(games = []) {
  return `<a class="feed-entry" href="#feed"><div><strong>Мои обновления</strong><p>${games.length ? 'Общая история ваших игр: обновления, новости и новые сборки.' : 'Добавьте игры и читайте их обновления в одной ленте.'}</p></div><span class="feed-entry-action">Открыть ${icon('arrow')}</span></a>`;
}

export function feedPage(data, library = []) {
  const { filters = { kind: 'all', days: 7 }, events = [], loading = false, loaded = false,
    error = '', hasMore = false, errorIsMore = false } = data;
  const header = `<a class="back-link" href="#library">${icon('arrow')}Библиотека</a>${pageHeader('Мои обновления', 'История игр из вашей библиотеки. Фильтры здесь не меняют уведомления.', '<button class="button secondary" type="button" data-action="feed-refresh" ' + (loading || !library.length ? 'disabled' : '') + '>' + icon('refresh') + 'Обновить ленту</button>')}`;
  if (!library.length) return header + emptyState('Сначала добавьте игры', 'Здесь появится общая история всех игр вашей библиотеки, даже если уведомления о них выключены.', '<a class="button primary" href="#search">Найти игру</a>');
  const choices = `<form id="feed-filters" class="feed-filters" aria-label="Фильтры истории"><label class="feed-filter" for="feed-game">Игра<select id="feed-game" name="app_id"><option value="">Все мои игры</option>${library.map(game => `<option value="${Number(game.app_id)}" ${Number(filters.app_id) === Number(game.app_id) ? 'selected' : ''}>${h(game.name)}</option>`).join('')}</select></label><label class="feed-filter" for="feed-days">Период<select id="feed-days" name="days">${[[7, 'За 7 дней'], [30, 'За 30 дней'], [0, 'Вся доступная история']].map(([value, label]) => `<option value="${value}" ${Number(filters.days) === value ? 'selected' : ''}>${label}</option>`).join('')}</select></label><label class="feed-filter" for="feed-kind">События<select id="feed-kind" name="kind">${[['all', 'Всё'], ['updates', 'Обновления'], ['news', 'Новости'], ['builds', 'Новые сборки']].map(([value, label]) => `<option value="${value}" ${filters.kind === value ? 'selected' : ''}>${label}</option>`).join('')}</select></label></form><p class="feed-explanation">${filters.kind === 'builds' ? 'Новая сборка — изменился технический номер игры в Steam. Что именно изменилось, может быть неизвестно.' : 'Читаем сохранённую историю. Она может быть неполной: у некоторых игр часть источников недоступна.'}</p>`;
  const cards = events.map(event => `<section class="feed-item"><h2 class="feed-game-heading"><a href="#game/${Number(event.app_id)}">${h(event.game_name || library.find(game => Number(game.app_id) === Number(event.app_id))?.name || `Игра Steam #${Number(event.app_id)}`)}</a></h2>${eventCard(event)}</section>`).join('');
  const empty = !events.length && loaded && !loading && !error ? emptyState('За этот период событий не найдено', 'Выберите другую игру, измените тип событий или откройте всю доступную историю.', '<button class="button secondary" type="button" data-action="feed-all">Показать всю историю</button>') : '';
  return `${header}${choices}<div id="feed-results" aria-busy="${loading ? 'true' : 'false'}"><div class="feed-timeline">${cards}</div>${empty}${loading ? loadingState(events.length ? 'Загружаем историю…' : 'Загружаем обновления ваших игр…') : ''}${error ? errorState(error, 'feed-retry') : ''}${!loading && hasMore && !error ? '<div class="load-more"><button class="button secondary" type="button" data-action="feed-more">Ещё из истории</button></div>' : ''}${!loading && loaded && events.length && !hasMore && !error ? '<p class="page-footnote">Это вся сохранённая история по выбранным фильтрам.</p>' : ''}</div>${error && errorIsMore ? '<p class="page-footnote">Загруженные события сохранены на экране. Повтор продолжит с той же страницы.</p>' : ''}`;
}

export function libraryTransferPanel() {
  return `<section id="library-transfer" class="library-transfer" aria-labelledby="library-transfer-title" hidden><div class="section-heading"><h2 id="library-transfer-title">Добавить несколько игр</h2><button class="button small quiet" type="button" data-action="library-transfer-close">Свернуть</button></div><p class="subtle">Вставьте ссылки магазина Steam или AppID — по одному на строку, через пробел или запятую. Можно загрузить сохранённый JSON-файл библиотеки. До 100 игр, файл до 256 КиБ.</p><form id="library-transfer-form"><label class="transfer-label" for="library-transfer-input">Список игр или содержимое файла</label><textarea id="library-transfer-input" rows="4" maxlength="262144" placeholder="https://store.steampowered.com/app/570/&#10;730&#10;578080" spellcheck="false"></textarea><div class="library-transfer-actions"><button class="button secondary" type="submit">Показать список</button><label class="button quiet transfer-file-label" for="library-transfer-file">Выбрать JSON-файл</label><input id="library-transfer-file" type="file" accept=".json,application/json" class="transfer-file-input"></div></form><div id="library-transfer-preview"></div><p id="library-transfer-message" class="transfer-message" role="status" aria-live="polite"></p><div id="library-export-copy" hidden><label class="transfer-label" for="library-export-text">Копия библиотеки с настройками игр</label><p class="subtle">Если Telegram не скачал файл, скопируйте этот текст и сохраните его. Его можно вставить в поле списка при восстановлении. Файл не содержит данные входа и историю уведомлений.</p><textarea id="library-export-text" rows="5" readonly spellcheck="false"></textarea><button class="button secondary" type="button" data-action="library-copy">Скопировать JSON</button></div></section>`;
}

export function eventCard(event, selected = false, preferred = 'ru') {
  const isBuild = event.kind === 'public_build_changed';
  const date = event.published_at || event.sort_at || event.detected_at;
  const source = sourceLabel(event.source);
  const language = publicationLanguage(event, preferred);
  const languageControls = selected && !isBuild ? language.originalRussian ? '<p class="translation-note">Исходная публикация на русском.</p>' : `<div class="publication-language" role="group" aria-label="Язык публикации"><button class="language-button ${language.russian || language.shortRussian ? 'selected' : ''}" type="button" data-action="language" data-event-id="${h(event.id)}" data-language="ru" ${!language.translated && !language.shortTranslated ? 'disabled' : ''}>Русский</button><button class="language-button ${!language.russian && !language.shortRussian ? 'selected' : ''}" type="button" data-action="language" data-event-id="${h(event.id)}" data-language="original">Оригинал</button></div><p class="translation-note">${language.shortRussian && !language.russian ? 'Готов краткий перевод. Полный текст ниже — оригинал.' : language.russian ? 'Автоматический перевод. Термины и числа можно сверить с оригиналом.' : language.translated ? 'Исходный текст разработчика.' : event.translation_status === 'pending' ? 'Русский перевод готовится. Сейчас показываем оригинал.' : event.short_translation_status === 'pending' ? 'Краткий перевод готовится. Сейчас показываем оригинал.' : 'Русский перевод пока недоступен. Показываем оригинал.'}</p>${!language.translated && event.translation_status !== 'pending' && event.contents?.trim() ? `<button class="button small secondary translate-button" type="button" data-action="translate" data-event-id="${h(event.id)}">Перевести полный текст</button>` : ''}` : '';
  return `<article class="event-card ${selected ? 'event-selected' : ''}" id="event-${h(String(event.id).replace(/[^a-zA-Z0-9_-]/g, '_'))}"><div class="event-meta"><span class="event-kind ${isBuild ? 'is-build' : event.kind === 'official_news_published' ? 'is-news' : ''}">${h(eventLabel(event))}</span><time datetime="${h(date || '')}">${h(formatDate(date, isBuild))}</time>${event.baseline ? '<span class="archive-label">Из доступной истории</span>' : ''}</div><h3>${selected ? h(language.title) : `<a href="${eventRoute(event)}">${h(language.title)}</a>`}</h3>
    ${eventEvidence(event, preferred, selected)}${languageControls}${isBuild ? `<p class="build-change"><span class="build-id-label">Номер сборки</span> ${h(event.old_build_id || 'неизвестен')} <span aria-label="сменился на">→</span> ${h(event.new_build_id || 'неизвестен')}</p><p class="subtle">Изменился технический номер сборки. Что именно изменилось, пока неизвестно: номер не доказывает наличие нового контента и не определяет важность обновления.</p>` : `${eventSummary(event, preferred)}${selected ? `<h4 class="full-publication-label">${language.shortRussian && !language.russian ? 'Полный текст — оригинал' : 'Полный полученный текст'}</h4>${language.contents ? `<div class="publication-text">${h(language.contents)}</div>` : '<p class="text-pending">Содержание пока не получено. Публикацию можно открыть у разработчика.</p>'}` : ''}`}${relatedSources(event, selected)}
    ${selected && language.russian && event.translation_truncated ? '<p class="notice">Перевод сокращён. Полный полученный текст доступен в разделе «Оригинал».</p>' : ''}${selected && event.contents_truncated ? '<p class="notice">Исходный текст сокращён; полная публикация доступна по ссылке на источник ниже.</p>' : ''}<div class="event-footer">${selected || isBuild ? '' : `<a class="text-link" href="${eventRoute(event)}">Читать полностью</a>`}${externalLink(event.url, source, 'source-link')}${selected ? `<a class="text-link close-event" href="#game/${event.app_id}">Свернуть</a>` : ''}</div>${selected && event.detected_at ? `<p class="event-detected">Сохранено ${h(formatDate(event.detected_at, true))}</p>` : ''}</article>`;
}

export function gamePage(data, library, eventId = null, paginationLoading = false, languages = {}) {
  const { game, events = [], pagination = {} } = data;
  const added = library.some(item => Number(item.app_id) === Number(game.app_id));
  const selectedFound = eventId && events.some(event => eventMatchesId(event, eventId));
  return `<a class="back-link" href="#library">${icon('arrow')}Библиотека</a><section class="game-heading"><div class="game-heading-copy"><span class="type-label">${applicationLabel(game, true)}</span><h1>${h(game.name)}</h1><div class="game-heading-actions">${addButton(game, library)}${added ? `<a class="button secondary" href="#settings/${game.app_id}">${icon('settings')}Настройки</a>` : ''}${externalLink(game.store_url, 'В Steam', 'text-link')}</div>${game.type === 'dlc' ? `<p class="parent-game">У дополнения может не быть собственной ленты обновлений. При необходимости добавьте ${game.parent_app_id ? `<a href="#game/${game.parent_app_id}">основную игру</a>` : 'основную игру'}.</p>` : game.type === 'steam_app' ? '<p class="parent-game">Приложение добавлено из библиотеки Steam, но его тип пока не подтверждён. Проверяем доступные источники обновлений.</p>' : ''}</div>${art(game, 'game-heading-art', false)}</section>
    <div class="coverage-bar"><div><span class="coverage-status status-${h(game.poll_status || 'awaiting')}"><i class="status-dot ${game.poll_status === 'ready' ? 'is-running' : ''}"></i>${h(coverageText(game))}</span>${game.last_polled_at ? `<small>Последняя проверка: ${h(formatDate(game.last_polled_at, true))}</small>` : '<small>Первые данные могут появиться не сразу.</small>'}${!added && !game.seed ? '<small>Добавьте игру в библиотеку, чтобы запустить проверку.</small>' : ''}</div><button class="button small secondary" type="button" data-action="refresh" data-app-id="${game.app_id}" ${!added && !game.seed ? 'disabled title="Сначала добавьте игру в библиотеку"' : ''}>${icon('refresh')}Проверить</button></div>
    <div class="section-heading timeline-heading"><h2>Что менялось в игре</h2>${game.build_id ? `<span class="subtle">Номер сборки ${h(game.build_id)}</span>` : ''}</div><p class="timeline-intro">Обновления, анонсы и технические сигналы о новой сборке. Объединяем источники только при явной связи. Если описание или важность неизвестны, это указано в карточке. Полная история Steam может быть недоступна.</p>
    ${eventId && !selectedFound ? '<div class="notice">Этого события ещё нет на загруженной странице. Загрузите следующую часть истории ниже.</div>' : ''}
    <div class="timeline">${events.length ? events.map(event => eventCard(event, eventMatchesId(event, eventId), languages[String(event.id)] || 'ru')).join('') : emptyState(game.poll_status === 'awaiting' ? 'Ожидаем первую проверку' : 'Сохранённых событий пока нет', game.poll_status === 'awaiting' ? 'Игра добавлена в очередь. Можно настроить уведомления; история появится после получения данных.' : 'Источник ещё не дал доступных событий. Попробуйте проверить игру снова.')}</div>
    ${pagination.has_more ? `<div class="load-more"><button class="button secondary" type="button" data-action="more" ${paginationLoading ? 'disabled' : ''}>${paginationLoading ? 'Загружаем…' : 'Ещё из истории'}</button></div>` : ''}`;
}

export function settingsPage(game) {
  const prefs = { ...DEFAULT_PREFS, ...game.preferences };
  return `<a class="back-link" href="#game/${game.app_id}">${icon('arrow')}${h(game.name)}</a>${pageHeader('Настройки уведомлений', 'Для ' + game.name)}
    <form id="preferences-form" class="preferences-form" data-app-id="${game.app_id}"><section class="settings-section"><label class="switch-row"><div><strong>Уведомления об этой игре</strong><p>Выбирает события для вашей ленты. Доставка в чат с ботом отдельно включается в библиотеке. Выключение сохраняет игру и её историю.</p></div><input name="enabled" type="checkbox" ${prefs.enabled ? 'checked' : ''}><span class="switch-visual" aria-hidden="true"></span></label></section>
    <section class="settings-section"><h2>Что присылать</h2><div class="mode-grid">${modesForPreferences(prefs).map(mode => `<label class="mode-option"><input type="radio" name="mode" value="${mode.id}" ${prefs.mode === mode.id ? 'checked' : ''}><div><strong>${h(mode.name)}${mode.id === 'updates' ? '<span class="recommended-label">Рекомендуем</span>' : ''}</strong><p>${h(mode.text)}</p></div></label>`).join('')}</div>
    <div id="custom-types" class="custom-types" ${prefs.mode !== 'custom' ? 'hidden' : ''}><h3>Типы событий</h3>${[['patches', 'Обновления игры и исправления'], ['news', 'Анонсы и новости разработчика'], ['builds', 'Технические сигналы без описания']].map(([name, label]) => `<label class="check-row"><input type="checkbox" name="${name}" ${prefs[name] ? 'checked' : ''}><span>${label}</span></label>`).join('')}</div>
    <div id="severity-note" class="notice severity-note" ${!['major', 'medium', 'minor'].includes(prefs.mode) ? 'hidden' : ''}>Важность определяем по явным признакам в тексте разработчика. Это приблизительная оценка: короткому или неясному описанию не приписываем важность.</div>
    <label id="unknown-option" class="check-row unknown-option" ${!['major', 'medium', 'minor'].includes(prefs.mode) ? 'hidden' : ''}><input type="checkbox" name="include_unknown" ${prefs.include_unknown ? 'checked' : ''}><div><strong>Также присылать обновления без оценки важности</strong><p>Помогает не пропустить обновление с неясным описанием. Такие карточки помечены «Важность пока неизвестна» и могут оказаться небольшими. Выключите, если хотите только уверенно определённые события.</p></div></label>
    <div id="noise-warning" class="notice noise-warning" ${prefs.mode !== 'all' && !(prefs.mode === 'custom' && prefs.builds) ? 'hidden' : ''}>Возможны частые уведомления. Номера сборок могут меняться несколько раз в день без заметного нового контента.</div></section>
    <section class="settings-section"><h2>Когда присылать</h2><label class="timing-option"><input name="timing" type="radio" value="described" ${prefs.timing === 'described' ? 'checked' : ''}><div><strong>Когда есть описание разработчика</strong><p>Ждём текст публикации и пропускаем технические сигналы без описания. Если описание так и не появится, сообщения не будет. Это не гарантирует, что разработчик уже рассказал всё.</p></div></label><label class="timing-option"><input name="timing" type="radio" value="fast" ${prefs.timing === 'fast' ? 'checked' : ''}><div><strong>Сразу после обнаружения</strong><p>Присылаем выбранные события с доступными данными. Карточка может дополниться позже; повторное сообщение о том же событии не обещаем.</p></div></label><p id="build-timing-note" class="subtle" ${(prefs.mode !== 'all' && !prefs.builds) || prefs.timing !== 'described' ? 'hidden' : ''}>Технические сигналы выбраны, но без описания сообщения о них не придут. Для ранних сигналов выберите «Сразу после обнаружения».</p></section>
    <div class="settings-save"><div id="preferences-message" role="status" aria-live="polite"></div><button class="button primary" type="submit">Сохранить настройки</button></div></form><div class="remove-game"><button class="button danger" type="button" data-action="remove" data-app-id="${game.app_id}">Убрать из библиотеки</button><p>Уведомления по этой игре прекратятся. Сохранённая история останется доступна; игру можно добавить снова.</p></div>`;
}

export function inboxPage(result, profile = {}, config = {}, deliveryStatus = {}) {
  const deliveryText = profile.local_only === false ? profile.telegram_delivery_enabled ? 'Новые уведомления также отправляются в Telegram. История сообщений остаётся здесь.' : 'Уведомления сохраняются здесь. Доставку в Telegram можно включить по своему выбору.' : 'Уведомления этого локального профиля приходят сюда. Для доставки в Telegram откройте приложение через бота.';
  const emptyDeliveryText = profile.local_only === false && profile.telegram_can_message && deliveryStatus.configured !== false && deliveryStatus.state !== 'blocked' ? ' Доставку в чат с ботом можно проверить кнопкой выше.' : '';
  return `${pageHeader('Уведомления', 'События, которые прошли ваши настройки.', result.unread_count ? '<button class="button secondary" type="button" data-action="read">Отметить прочитанными</button>' : '')}${deliveryControls(profile, config, deliveryStatus)}<div class="delivery-note"><span class="note-mark" aria-hidden="true">i</span><p>${h(deliveryText)} Включение доставки и смена режима действуют на новые события; старые сообщения не отправляются заново.</p></div>${result.items?.length ? `<div class="inbox-list">${result.items.map(item => `<article class="inbox-item ${item.read ? '' : 'is-unread'}"><div class="inbox-marker" aria-hidden="true"></div><div class="inbox-content"><div class="event-meta"><a class="inbox-game" href="#game/${item.event.app_id}">${h(item.event.game_name)}</a><span>${h(eventLabel(item.event))}</span><time>${h(formatDate(item.created_at, true))}</time></div><h2><a href="${eventRoute(item.event)}">${h(publicationLanguage(item.event).title)}</a></h2>${eventEvidence(item.event)}${eventSummary(item.event, 'ru', true)}<div class="inbox-reason">${icon('settings')}<span>${h(item.reason || 'Соответствует настройкам игры.')}</span><a href="#settings/${item.event.app_id}">Изменить</a></div></div></article>`).join('')}</div>` : emptyState('Пока тихо', 'Сообщения появятся после новых подходящих событий. Отсутствие сообщений ещё не означает ошибку: старую историю и события, отклонённые прежними настройками, не рассылаем.' + emptyDeliveryText, '<a class="button secondary" href="#library">Посмотреть библиотеку</a>')}`;
}
